//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsRegulatoryClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/ParmItemSrv.asmx")]
        public string HSIS_Client_ParmItemSrv_ParmItemSrv {
            get {
                return ((string)(this["HSIS_Client_ParmItemSrv_ParmItemSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/BaseManagerSrv.asmx")]
        public string HSIS_Client_BaseManagerSrv_BaseManagerSrv {
            get {
                return ((string)(this["HSIS_Client_BaseManagerSrv_BaseManagerSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/CommonManagerSrv.asmx")]
        public string HSIS_Client_CommonManagerSrv_CommonManagerSrv {
            get {
                return ((string)(this["HSIS_Client_CommonManagerSrv_CommonManagerSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/UserManageSrv.asmx")]
        public string HSIS_Client_UserManageSrv_UserManageSrv {
            get {
                return ((string)(this["HSIS_Client_UserManageSrv_UserManageSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/UserDutyManagerSrv.asmx")]
        public string HSIS_Client_UserDutyManagerSrv_UserDutyManagerSrv {
            get {
                return ((string)(this["HSIS_Client_UserDutyManagerSrv_UserDutyManagerSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/DutyManageSrv.asmx")]
        public string HSIS_Client_DutyManageSrv_DutyManageSrv {
            get {
                return ((string)(this["HSIS_Client_DutyManageSrv_DutyManageSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/FunSrv.asmx")]
        public string HSIS_Client_FunSrv_FunSrv {
            get {
                return ((string)(this["HSIS_Client_FunSrv_FunSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_AccountManageService.asmx")]
        public string Client_JG_AccountManageSrv_JG_AccountManageService {
            get {
                return ((string)(this["Client_JG_AccountManageSrv_JG_AccountManageService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_AmountCollectService.asmx")]
        public string Client_JG_AmountCollectSrv_JG_AmountCollectService {
            get {
                return ((string)(this["Client_JG_AmountCollectSrv_JG_AmountCollectService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_MessageInfoService.asmx")]
        public string Client_JG_MessageInfoSrv_JG_MessageInfoService {
            get {
                return ((string)(this["Client_JG_MessageInfoSrv_JG_MessageInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_BranchesService.asmx")]
        public string Client_JG_BranchesSrv_JG_BranchesService {
            get {
                return ((string)(this["Client_JG_BranchesSrv_JG_BranchesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_SpvProtocolService.asmx")]
        public string Client_JG_SpvProtocolSrv_JG_SpvProtocolService {
            get {
                return ((string)(this["Client_JG_SpvProtocolSrv_JG_SpvProtocolService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_DepositService.asmx")]
        public string Client_JG_DepositSrv_JG_DepositService {
            get {
                return ((string)(this["Client_JG_DepositSrv_JG_DepositService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/BillSrv.asmx")]
        public string Client_BillSrv_BillSrv {
            get {
                return ((string)(this["Client_BillSrv_BillSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/HelpService.asmx")]
        public string Client_HelpSrv_HelpService {
            get {
                return ((string)(this["Client_HelpSrv_HelpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/RegulatorySrv.asmx")]
        public string FundsRegulatoryClient_RegulatorySrv_RegulatorySrv {
            get {
                return ((string)(this["FundsRegulatoryClient_RegulatorySrv_RegulatorySrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/SysConfigService.asmx")]
        public string FundsRegulatoryClient_SysConfigSrv_SysConfigService {
            get {
                return ((string)(this["FundsRegulatoryClient_SysConfigSrv_SysConfigService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_InterestRateSrv.asmx")]
        public string FinancialRegulationClient_JG_InterestRateSrv_JG_InterestRateSrv {
            get {
                return ((string)(this["FinancialRegulationClient_JG_InterestRateSrv_JG_InterestRateSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSrv/BasicFunctionSrv.asmx")]
        public string FinancialRegulationClient_BasicFunctionSrv_BasicFunctionSrv {
            get {
                return ((string)(this["FinancialRegulationClient_BasicFunctionSrv_BasicFunctionSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/BillOperateSrv.asmx")]
        public string FinancialRegulationClient_BillOperateSrv_BillOperateSrv {
            get {
                return ((string)(this["FinancialRegulationClient_BillOperateSrv_BillOperateSrv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_AdjustService.asmx")]
        public string FinancialRegulationClient_JG_AdjustSrv_JG_AdjustService {
            get {
                return ((string)(this["FinancialRegulationClient_JG_AdjustSrv_JG_AdjustService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/InterestService.asmx")]
        public string FinancialRegulationClient_InterestService_InterestService {
            get {
                return ((string)(this["FinancialRegulationClient_InterestService_InterestService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/RefunTradeService.asmx")]
        public string FinancialRegulationClient_RefunTradeSrv_RefunTradeService {
            get {
                return ((string)(this["FinancialRegulationClient_RefunTradeSrv_RefunTradeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/SqlTrans.asmx")]
        public string FinancialRegulationClient_SqlTransSvr_SqlTrans {
            get {
                return ((string)(this["FinancialRegulationClient_SqlTransSvr_SqlTrans"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FinancialRegulationSRV/JG_PaymentService.asmx")]
        public string FinancialRegulationClient_JG_PaymentSrv_JG_PaymentService {
            get {
                return ((string)(this["FinancialRegulationClient_JG_PaymentSrv_JG_PaymentService"]));
            }
        }
    }
}
