//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.JG_SpvProtocolSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JG_SpvProtocolServiceSoap", Namespace="http://tempuri.org/")]
    public partial class JG_SpvProtocolService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProtocolByConditionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JG_SpvProtocolService() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.Client_JG_SpvProtocolSrv_JG_SpvProtocolService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event SelectsCompletedEventHandler SelectsCompleted;
        
        /// <remarks/>
        public event SelectCompletedEventHandler SelectCompleted;
        
        /// <remarks/>
        public event GetProtocolByConditionCompletedEventHandler GetProtocolByConditionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(JG_SpvProtocol o) {
            object[] results = this.Invoke("Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(JG_SpvProtocol o) {
            this.AddAsync(o, null);
        }
        
        /// <remarks/>
        public void AddAsync(JG_SpvProtocol o, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        o}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update(JG_SpvProtocol o) {
            object[] results = this.Invoke("Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(JG_SpvProtocol o) {
            this.UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(JG_SpvProtocol o, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        o}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(JG_SpvProtocol o) {
            object[] results = this.Invoke("Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(JG_SpvProtocol o) {
            this.DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(JG_SpvProtocol o, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        o}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JG_SpvProtocol[] Selects() {
            object[] results = this.Invoke("Selects", new object[0]);
            return ((JG_SpvProtocol[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectsAsync() {
            this.SelectsAsync(null);
        }
        
        /// <remarks/>
        public void SelectsAsync(object userState) {
            if ((this.SelectsOperationCompleted == null)) {
                this.SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectsOperationCompleted);
            }
            this.InvokeAsync("Selects", new object[0], this.SelectsOperationCompleted, userState);
        }
        
        private void OnSelectsOperationCompleted(object arg) {
            if ((this.SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectsCompleted(this, new SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JG_SpvProtocol[] Select(JG_SpvProtocol o) {
            object[] results = this.Invoke("Select", new object[] {
                        o});
            return ((JG_SpvProtocol[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectAsync(JG_SpvProtocol o) {
            this.SelectAsync(o, null);
        }
        
        /// <remarks/>
        public void SelectAsync(JG_SpvProtocol o, object userState) {
            if ((this.SelectOperationCompleted == null)) {
                this.SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOperationCompleted);
            }
            this.InvokeAsync("Select", new object[] {
                        o}, this.SelectOperationCompleted, userState);
        }
        
        private void OnSelectOperationCompleted(object arg) {
            if ((this.SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompleted(this, new SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProtocolByCondition", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JG_SpvProtocol[] GetProtocolByCondition(JG_SpvProtocol jG_SpvProtocol, string token) {
            object[] results = this.Invoke("GetProtocolByCondition", new object[] {
                        jG_SpvProtocol,
                        token});
            return ((JG_SpvProtocol[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProtocolByConditionAsync(JG_SpvProtocol jG_SpvProtocol, string token) {
            this.GetProtocolByConditionAsync(jG_SpvProtocol, token, null);
        }
        
        /// <remarks/>
        public void GetProtocolByConditionAsync(JG_SpvProtocol jG_SpvProtocol, string token, object userState) {
            if ((this.GetProtocolByConditionOperationCompleted == null)) {
                this.GetProtocolByConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProtocolByConditionOperationCompleted);
            }
            this.InvokeAsync("GetProtocolByCondition", new object[] {
                        jG_SpvProtocol,
                        token}, this.GetProtocolByConditionOperationCompleted, userState);
        }
        
        private void OnGetProtocolByConditionOperationCompleted(object arg) {
            if ((this.GetProtocolByConditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProtocolByConditionCompleted(this, new GetProtocolByConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JG_SpvProtocol {
        
        private string sP_IDField;
        
        private string sP_SaleItemIDField;
        
        private string sP_XYBHField;
        
        private string sP_JGJGField;
        
        private string sP_CorpCodeField;
        
        private string sP_CorpNameField;
        
        private string sP_QMField;
        
        private string sP_ItemSiteField;
        
        private string sP_ItemNameField;
        
        private decimal sP_JZMJField;
        
        private string sP_BuildingNoField;
        
        private decimal sP_GCJSFField;
        
        private decimal sP_BKYJFField;
        
        private decimal sP_ZDJGYSKField;
        
        private string sP_QYZHMCField;
        
        private string sP_QYKHYHBHField;
        
        private string sP_QYKHYHField;
        
        private string sP_QYZHField;
        
        private string sP_JGJGZHMCField;
        
        private string sP_JGJGKHYHBHField;
        
        private string sP_JGJGKHYHField;
        
        private string sP_JGJGZHField;
        
        private string sP_XYLCField;
        
        private string sP_XYLCNameField;
        
        private string sP_XYZTField;
        
        private string sP_XYZTNameField;
        
        private string sP_IsRejectField;
        
        private string sP_IsRejectNameField;
        
        private string sP_QYLXDHField;
        
        private string sP_LXRField;
        
        private string sP_LXRDHField;
        
        private string sP_JZXField;
        
        private string sP_BZField;
        
        private System.DateTime sP_CreateDateField;
        
        private string sP_ZYJJFSField;
        
        private System.DateTime sP_PrtlSaveDateField;
        
        /// <remarks/>
        public string SP_ID {
            get {
                return this.sP_IDField;
            }
            set {
                this.sP_IDField = value;
            }
        }
        
        /// <remarks/>
        public string SP_SaleItemID {
            get {
                return this.sP_SaleItemIDField;
            }
            set {
                this.sP_SaleItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string SP_XYBH {
            get {
                return this.sP_XYBHField;
            }
            set {
                this.sP_XYBHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JGJG {
            get {
                return this.sP_JGJGField;
            }
            set {
                this.sP_JGJGField = value;
            }
        }
        
        /// <remarks/>
        public string SP_CorpCode {
            get {
                return this.sP_CorpCodeField;
            }
            set {
                this.sP_CorpCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SP_CorpName {
            get {
                return this.sP_CorpNameField;
            }
            set {
                this.sP_CorpNameField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QM {
            get {
                return this.sP_QMField;
            }
            set {
                this.sP_QMField = value;
            }
        }
        
        /// <remarks/>
        public string SP_ItemSite {
            get {
                return this.sP_ItemSiteField;
            }
            set {
                this.sP_ItemSiteField = value;
            }
        }
        
        /// <remarks/>
        public string SP_ItemName {
            get {
                return this.sP_ItemNameField;
            }
            set {
                this.sP_ItemNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal SP_JZMJ {
            get {
                return this.sP_JZMJField;
            }
            set {
                this.sP_JZMJField = value;
            }
        }
        
        /// <remarks/>
        public string SP_BuildingNo {
            get {
                return this.sP_BuildingNoField;
            }
            set {
                this.sP_BuildingNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal SP_GCJSF {
            get {
                return this.sP_GCJSFField;
            }
            set {
                this.sP_GCJSFField = value;
            }
        }
        
        /// <remarks/>
        public decimal SP_BKYJF {
            get {
                return this.sP_BKYJFField;
            }
            set {
                this.sP_BKYJFField = value;
            }
        }
        
        /// <remarks/>
        public decimal SP_ZDJGYSK {
            get {
                return this.sP_ZDJGYSKField;
            }
            set {
                this.sP_ZDJGYSKField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QYZHMC {
            get {
                return this.sP_QYZHMCField;
            }
            set {
                this.sP_QYZHMCField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QYKHYHBH {
            get {
                return this.sP_QYKHYHBHField;
            }
            set {
                this.sP_QYKHYHBHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QYKHYH {
            get {
                return this.sP_QYKHYHField;
            }
            set {
                this.sP_QYKHYHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QYZH {
            get {
                return this.sP_QYZHField;
            }
            set {
                this.sP_QYZHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JGJGZHMC {
            get {
                return this.sP_JGJGZHMCField;
            }
            set {
                this.sP_JGJGZHMCField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JGJGKHYHBH {
            get {
                return this.sP_JGJGKHYHBHField;
            }
            set {
                this.sP_JGJGKHYHBHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JGJGKHYH {
            get {
                return this.sP_JGJGKHYHField;
            }
            set {
                this.sP_JGJGKHYHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JGJGZH {
            get {
                return this.sP_JGJGZHField;
            }
            set {
                this.sP_JGJGZHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_XYLC {
            get {
                return this.sP_XYLCField;
            }
            set {
                this.sP_XYLCField = value;
            }
        }
        
        /// <remarks/>
        public string SP_XYLCName {
            get {
                return this.sP_XYLCNameField;
            }
            set {
                this.sP_XYLCNameField = value;
            }
        }
        
        /// <remarks/>
        public string SP_XYZT {
            get {
                return this.sP_XYZTField;
            }
            set {
                this.sP_XYZTField = value;
            }
        }
        
        /// <remarks/>
        public string SP_XYZTName {
            get {
                return this.sP_XYZTNameField;
            }
            set {
                this.sP_XYZTNameField = value;
            }
        }
        
        /// <remarks/>
        public string SP_IsReject {
            get {
                return this.sP_IsRejectField;
            }
            set {
                this.sP_IsRejectField = value;
            }
        }
        
        /// <remarks/>
        public string SP_IsRejectName {
            get {
                return this.sP_IsRejectNameField;
            }
            set {
                this.sP_IsRejectNameField = value;
            }
        }
        
        /// <remarks/>
        public string SP_QYLXDH {
            get {
                return this.sP_QYLXDHField;
            }
            set {
                this.sP_QYLXDHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_LXR {
            get {
                return this.sP_LXRField;
            }
            set {
                this.sP_LXRField = value;
            }
        }
        
        /// <remarks/>
        public string SP_LXRDH {
            get {
                return this.sP_LXRDHField;
            }
            set {
                this.sP_LXRDHField = value;
            }
        }
        
        /// <remarks/>
        public string SP_JZX {
            get {
                return this.sP_JZXField;
            }
            set {
                this.sP_JZXField = value;
            }
        }
        
        /// <remarks/>
        public string SP_BZ {
            get {
                return this.sP_BZField;
            }
            set {
                this.sP_BZField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SP_CreateDate {
            get {
                return this.sP_CreateDateField;
            }
            set {
                this.sP_CreateDateField = value;
            }
        }
        
        /// <remarks/>
        public string SP_ZYJJFS {
            get {
                return this.sP_ZYJJFSField;
            }
            set {
                this.sP_ZYJJFSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SP_PrtlSaveDate {
            get {
                return this.sP_PrtlSaveDateField;
            }
            set {
                this.sP_PrtlSaveDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectsCompletedEventHandler(object sender, SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JG_SpvProtocol[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JG_SpvProtocol[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectCompletedEventHandler(object sender, SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JG_SpvProtocol[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JG_SpvProtocol[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetProtocolByConditionCompletedEventHandler(object sender, GetProtocolByConditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProtocolByConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProtocolByConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JG_SpvProtocol[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JG_SpvProtocol[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591