//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.JG_InterestRateSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JG_InterestRateSrvSoap", Namespace="http://tempuri.org/")]
    public partial class JG_InterestRateSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectJG_InterestRateInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddJG_InterestRateInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateJG_InterestRateInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InterestInquireOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JG_InterestRateSrv() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.FinancialRegulationClient_JG_InterestRateSrv_JG_InterestRateSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectJG_InterestRateInfoCompletedEventHandler SelectJG_InterestRateInfoCompleted;
        
        /// <remarks/>
        public event AddJG_InterestRateInfoCompletedEventHandler AddJG_InterestRateInfoCompleted;
        
        /// <remarks/>
        public event UpdateJG_InterestRateInfoCompletedEventHandler UpdateJG_InterestRateInfoCompleted;
        
        /// <remarks/>
        public event InterestInquireCompletedEventHandler InterestInquireCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectJG_InterestRateInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JG_InterestRateInfo[] SelectJG_InterestRateInfo() {
            object[] results = this.Invoke("SelectJG_InterestRateInfo", new object[0]);
            return ((JG_InterestRateInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectJG_InterestRateInfoAsync() {
            this.SelectJG_InterestRateInfoAsync(null);
        }
        
        /// <remarks/>
        public void SelectJG_InterestRateInfoAsync(object userState) {
            if ((this.SelectJG_InterestRateInfoOperationCompleted == null)) {
                this.SelectJG_InterestRateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectJG_InterestRateInfoOperationCompleted);
            }
            this.InvokeAsync("SelectJG_InterestRateInfo", new object[0], this.SelectJG_InterestRateInfoOperationCompleted, userState);
        }
        
        private void OnSelectJG_InterestRateInfoOperationCompleted(object arg) {
            if ((this.SelectJG_InterestRateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectJG_InterestRateInfoCompleted(this, new SelectJG_InterestRateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddJG_InterestRateInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddJG_InterestRateInfo(JG_InterestRateInfo jirInfo) {
            object[] results = this.Invoke("AddJG_InterestRateInfo", new object[] {
                        jirInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddJG_InterestRateInfoAsync(JG_InterestRateInfo jirInfo) {
            this.AddJG_InterestRateInfoAsync(jirInfo, null);
        }
        
        /// <remarks/>
        public void AddJG_InterestRateInfoAsync(JG_InterestRateInfo jirInfo, object userState) {
            if ((this.AddJG_InterestRateInfoOperationCompleted == null)) {
                this.AddJG_InterestRateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddJG_InterestRateInfoOperationCompleted);
            }
            this.InvokeAsync("AddJG_InterestRateInfo", new object[] {
                        jirInfo}, this.AddJG_InterestRateInfoOperationCompleted, userState);
        }
        
        private void OnAddJG_InterestRateInfoOperationCompleted(object arg) {
            if ((this.AddJG_InterestRateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddJG_InterestRateInfoCompleted(this, new AddJG_InterestRateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateJG_InterestRateInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateJG_InterestRateInfo(JG_InterestRateInfo jirInfo) {
            object[] results = this.Invoke("UpdateJG_InterestRateInfo", new object[] {
                        jirInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateJG_InterestRateInfoAsync(JG_InterestRateInfo jirInfo) {
            this.UpdateJG_InterestRateInfoAsync(jirInfo, null);
        }
        
        /// <remarks/>
        public void UpdateJG_InterestRateInfoAsync(JG_InterestRateInfo jirInfo, object userState) {
            if ((this.UpdateJG_InterestRateInfoOperationCompleted == null)) {
                this.UpdateJG_InterestRateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateJG_InterestRateInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateJG_InterestRateInfo", new object[] {
                        jirInfo}, this.UpdateJG_InterestRateInfoOperationCompleted, userState);
        }
        
        private void OnUpdateJG_InterestRateInfoOperationCompleted(object arg) {
            if ((this.UpdateJG_InterestRateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateJG_InterestRateInfoCompleted(this, new UpdateJG_InterestRateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InterestInquire", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal InterestInquire(string protocolNo) {
            object[] results = this.Invoke("InterestInquire", new object[] {
                        protocolNo});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void InterestInquireAsync(string protocolNo) {
            this.InterestInquireAsync(protocolNo, null);
        }
        
        /// <remarks/>
        public void InterestInquireAsync(string protocolNo, object userState) {
            if ((this.InterestInquireOperationCompleted == null)) {
                this.InterestInquireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInterestInquireOperationCompleted);
            }
            this.InvokeAsync("InterestInquire", new object[] {
                        protocolNo}, this.InterestInquireOperationCompleted, userState);
        }
        
        private void OnInterestInquireOperationCompleted(object arg) {
            if ((this.InterestInquireCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InterestInquireCompleted(this, new InterestInquireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JG_InterestRateInfo {
        
        private string idField;
        
        private System.Nullable<decimal> interestRateField;
        
        private System.DateTime setDateField;
        
        private string remarkField;
        
        private string flagField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> InterestRate {
            get {
                return this.interestRateField;
            }
            set {
                this.interestRateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SetDate {
            get {
                return this.setDateField;
            }
            set {
                this.setDateField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectJG_InterestRateInfoCompletedEventHandler(object sender, SelectJG_InterestRateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectJG_InterestRateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectJG_InterestRateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JG_InterestRateInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JG_InterestRateInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddJG_InterestRateInfoCompletedEventHandler(object sender, AddJG_InterestRateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddJG_InterestRateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddJG_InterestRateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateJG_InterestRateInfoCompletedEventHandler(object sender, UpdateJG_InterestRateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateJG_InterestRateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateJG_InterestRateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InterestInquireCompletedEventHandler(object sender, InterestInquireCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterestInquireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InterestInquireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591