//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.JG_DepositSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JG_DepositServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DictionaryEntry[]))]
    public partial class JG_DepositService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectnOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectDepositInfoListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUnKownJG_DepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUnKownJG_DepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUnKownJG_DepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUnKownJG_DepositOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JG_DepositService() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.Client_JG_DepositSrv_JG_DepositService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event SelectsCompletedEventHandler SelectsCompleted;
        
        /// <remarks/>
        public event SelectCompletedEventHandler SelectCompleted;
        
        /// <remarks/>
        public event GetAccountMoneyCompletedEventHandler GetAccountMoneyCompleted;
        
        /// <remarks/>
        public event SelectnCompletedEventHandler SelectnCompleted;
        
        /// <remarks/>
        public event SelectDepositInfoListCompletedEventHandler SelectDepositInfoListCompleted;
        
        /// <remarks/>
        public event AddUnKownJG_DepositCompletedEventHandler AddUnKownJG_DepositCompleted;
        
        /// <remarks/>
        public event UpdateUnKownJG_DepositCompletedEventHandler UpdateUnKownJG_DepositCompleted;
        
        /// <remarks/>
        public event SelectUnKownJG_DepositCompletedEventHandler SelectUnKownJG_DepositCompleted;
        
        /// <remarks/>
        public event DeleteUnKownJG_DepositCompletedEventHandler DeleteUnKownJG_DepositCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(DepositFund o) {
            object[] results = this.Invoke("Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(DepositFund o) {
            this.AddAsync(o, null);
        }
        
        /// <remarks/>
        public void AddAsync(DepositFund o, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        o}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update(DepositFund o) {
            object[] results = this.Invoke("Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(DepositFund o) {
            this.UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(DepositFund o, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        o}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(DepositFund o) {
            object[] results = this.Invoke("Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(DepositFund o) {
            this.DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(DepositFund o, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        o}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepositFund[] Selects() {
            object[] results = this.Invoke("Selects", new object[0]);
            return ((DepositFund[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectsAsync() {
            this.SelectsAsync(null);
        }
        
        /// <remarks/>
        public void SelectsAsync(object userState) {
            if ((this.SelectsOperationCompleted == null)) {
                this.SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectsOperationCompleted);
            }
            this.InvokeAsync("Selects", new object[0], this.SelectsOperationCompleted, userState);
        }
        
        private void OnSelectsOperationCompleted(object arg) {
            if ((this.SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectsCompleted(this, new SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepositFund[] Select(DepositFund o) {
            object[] results = this.Invoke("Select", new object[] {
                        o});
            return ((DepositFund[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectAsync(DepositFund o) {
            this.SelectAsync(o, null);
        }
        
        /// <remarks/>
        public void SelectAsync(DepositFund o, object userState) {
            if ((this.SelectOperationCompleted == null)) {
                this.SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOperationCompleted);
            }
            this.InvokeAsync("Select", new object[] {
                        o}, this.SelectOperationCompleted, userState);
        }
        
        private void OnSelectOperationCompleted(object arg) {
            if ((this.SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompleted(this, new SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAccountMoney(string xybh) {
            object[] results = this.Invoke("GetAccountMoney", new object[] {
                        xybh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountMoneyAsync(string xybh) {
            this.GetAccountMoneyAsync(xybh, null);
        }
        
        /// <remarks/>
        public void GetAccountMoneyAsync(string xybh, object userState) {
            if ((this.GetAccountMoneyOperationCompleted == null)) {
                this.GetAccountMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountMoneyOperationCompleted);
            }
            this.InvokeAsync("GetAccountMoney", new object[] {
                        xybh}, this.GetAccountMoneyOperationCompleted, userState);
        }
        
        private void OnGetAccountMoneyOperationCompleted(object arg) {
            if ((this.GetAccountMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountMoneyCompleted(this, new GetAccountMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Selectn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepositFund[] Selectn(DepositFund info) {
            object[] results = this.Invoke("Selectn", new object[] {
                        info});
            return ((DepositFund[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectnAsync(DepositFund info) {
            this.SelectnAsync(info, null);
        }
        
        /// <remarks/>
        public void SelectnAsync(DepositFund info, object userState) {
            if ((this.SelectnOperationCompleted == null)) {
                this.SelectnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectnOperationCompleted);
            }
            this.InvokeAsync("Selectn", new object[] {
                        info}, this.SelectnOperationCompleted, userState);
        }
        
        private void OnSelectnOperationCompleted(object arg) {
            if ((this.SelectnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectnCompleted(this, new SelectnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectDepositInfoList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepositFund[] SelectDepositInfoList([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] array) {
            object[] results = this.Invoke("SelectDepositInfoList", new object[] {
                        array});
            return ((DepositFund[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectDepositInfoListAsync(DictionaryEntry[] array) {
            this.SelectDepositInfoListAsync(array, null);
        }
        
        /// <remarks/>
        public void SelectDepositInfoListAsync(DictionaryEntry[] array, object userState) {
            if ((this.SelectDepositInfoListOperationCompleted == null)) {
                this.SelectDepositInfoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectDepositInfoListOperationCompleted);
            }
            this.InvokeAsync("SelectDepositInfoList", new object[] {
                        array}, this.SelectDepositInfoListOperationCompleted, userState);
        }
        
        private void OnSelectDepositInfoListOperationCompleted(object arg) {
            if ((this.SelectDepositInfoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectDepositInfoListCompleted(this, new SelectDepositInfoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddUnKownJG_Deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUnKownJG_Deposit(UnknowBill jdInfo) {
            object[] results = this.Invoke("AddUnKownJG_Deposit", new object[] {
                        jdInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUnKownJG_DepositAsync(UnknowBill jdInfo) {
            this.AddUnKownJG_DepositAsync(jdInfo, null);
        }
        
        /// <remarks/>
        public void AddUnKownJG_DepositAsync(UnknowBill jdInfo, object userState) {
            if ((this.AddUnKownJG_DepositOperationCompleted == null)) {
                this.AddUnKownJG_DepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUnKownJG_DepositOperationCompleted);
            }
            this.InvokeAsync("AddUnKownJG_Deposit", new object[] {
                        jdInfo}, this.AddUnKownJG_DepositOperationCompleted, userState);
        }
        
        private void OnAddUnKownJG_DepositOperationCompleted(object arg) {
            if ((this.AddUnKownJG_DepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUnKownJG_DepositCompleted(this, new AddUnKownJG_DepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUnKownJG_Deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUnKownJG_Deposit(UnknowBill jdInfo) {
            object[] results = this.Invoke("UpdateUnKownJG_Deposit", new object[] {
                        jdInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUnKownJG_DepositAsync(UnknowBill jdInfo) {
            this.UpdateUnKownJG_DepositAsync(jdInfo, null);
        }
        
        /// <remarks/>
        public void UpdateUnKownJG_DepositAsync(UnknowBill jdInfo, object userState) {
            if ((this.UpdateUnKownJG_DepositOperationCompleted == null)) {
                this.UpdateUnKownJG_DepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUnKownJG_DepositOperationCompleted);
            }
            this.InvokeAsync("UpdateUnKownJG_Deposit", new object[] {
                        jdInfo}, this.UpdateUnKownJG_DepositOperationCompleted, userState);
        }
        
        private void OnUpdateUnKownJG_DepositOperationCompleted(object arg) {
            if ((this.UpdateUnKownJG_DepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUnKownJG_DepositCompleted(this, new UpdateUnKownJG_DepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectUnKownJG_Deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnknowBill[] SelectUnKownJG_Deposit() {
            object[] results = this.Invoke("SelectUnKownJG_Deposit", new object[0]);
            return ((UnknowBill[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectUnKownJG_DepositAsync() {
            this.SelectUnKownJG_DepositAsync(null);
        }
        
        /// <remarks/>
        public void SelectUnKownJG_DepositAsync(object userState) {
            if ((this.SelectUnKownJG_DepositOperationCompleted == null)) {
                this.SelectUnKownJG_DepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUnKownJG_DepositOperationCompleted);
            }
            this.InvokeAsync("SelectUnKownJG_Deposit", new object[0], this.SelectUnKownJG_DepositOperationCompleted, userState);
        }
        
        private void OnSelectUnKownJG_DepositOperationCompleted(object arg) {
            if ((this.SelectUnKownJG_DepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUnKownJG_DepositCompleted(this, new SelectUnKownJG_DepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUnKownJG_Deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUnKownJG_Deposit(UnknowBill jdInfo) {
            object[] results = this.Invoke("DeleteUnKownJG_Deposit", new object[] {
                        jdInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUnKownJG_DepositAsync(UnknowBill jdInfo) {
            this.DeleteUnKownJG_DepositAsync(jdInfo, null);
        }
        
        /// <remarks/>
        public void DeleteUnKownJG_DepositAsync(UnknowBill jdInfo, object userState) {
            if ((this.DeleteUnKownJG_DepositOperationCompleted == null)) {
                this.DeleteUnKownJG_DepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUnKownJG_DepositOperationCompleted);
            }
            this.InvokeAsync("DeleteUnKownJG_Deposit", new object[] {
                        jdInfo}, this.DeleteUnKownJG_DepositOperationCompleted, userState);
        }
        
        private void OnDeleteUnKownJG_DepositOperationCompleted(object arg) {
            if ((this.DeleteUnKownJG_DepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUnKownJG_DepositCompleted(this, new DeleteUnKownJG_DepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositFund {
        
        private string idField;
        
        private string packageLengthField;
        
        private string businessCodeField;
        
        private string bankCodeField;
        
        private string depositNumField;
        
        private System.Nullable<decimal> depositAmountField;
        
        private string purchaserNameField;
        
        private string purchaserIDField;
        
        private string bankNameField;
        
        private string bankSiteIDField;
        
        private string bankTellerIDField;
        
        private string serialNumberField;
        
        private string depositInstrField;
        
        private System.Nullable<System.DateTime> depositTimeField;
        
        private string deSerialNumberField;
        
        private string depositStateField;
        
        private string firmNameField;
        
        private string depositAccountField;
        
        private string depositTypeField;
        
        private string projectCodeField;
        
        private System.Nullable<System.DateTime> checkTimeField;
        
        private string reverseInstrField;
        
        private System.Nullable<System.DateTime> reverseTimeField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PackageLength {
            get {
                return this.packageLengthField;
            }
            set {
                this.packageLengthField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DepositNum {
            get {
                return this.depositNumField;
            }
            set {
                this.depositNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DepositAmount {
            get {
                return this.depositAmountField;
            }
            set {
                this.depositAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaserName {
            get {
                return this.purchaserNameField;
            }
            set {
                this.purchaserNameField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaserID {
            get {
                return this.purchaserIDField;
            }
            set {
                this.purchaserIDField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankSiteID {
            get {
                return this.bankSiteIDField;
            }
            set {
                this.bankSiteIDField = value;
            }
        }
        
        /// <remarks/>
        public string BankTellerID {
            get {
                return this.bankTellerIDField;
            }
            set {
                this.bankTellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DepositInstr {
            get {
                return this.depositInstrField;
            }
            set {
                this.depositInstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DepositTime {
            get {
                return this.depositTimeField;
            }
            set {
                this.depositTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DeSerialNumber {
            get {
                return this.deSerialNumberField;
            }
            set {
                this.deSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DepositState {
            get {
                return this.depositStateField;
            }
            set {
                this.depositStateField = value;
            }
        }
        
        /// <remarks/>
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        public string DepositAccount {
            get {
                return this.depositAccountField;
            }
            set {
                this.depositAccountField = value;
            }
        }
        
        /// <remarks/>
        public string DepositType {
            get {
                return this.depositTypeField;
            }
            set {
                this.depositTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CheckTime {
            get {
                return this.checkTimeField;
            }
            set {
                this.checkTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReverseInstr {
            get {
                return this.reverseInstrField;
            }
            set {
                this.reverseInstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReverseTime {
            get {
                return this.reverseTimeField;
            }
            set {
                this.reverseTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UnknowBill {
        
        private string packageLengthField;
        
        private string businessCodeField;
        
        private string uB_BankCodeField;
        
        private string uB_IDField;
        
        private string uB_FirmNameField;
        
        private string uB_ManageAccountField;
        
        private System.Nullable<decimal> uB_MoneyField;
        
        private System.Nullable<System.DateTime> uB_TimeField;
        
        private string uB_PayerNameField;
        
        private string uB_PayerAccountField;
        
        private string uB_TypeField;
        
        private string uB_BankSerialNumField;
        
        private string uB_SerialNumField;
        
        private string uB_BankSiteIDField;
        
        private string uB_BankTellerIDField;
        
        private string uB_RemarkField;
        
        private string uB_StateField;
        
        private string uB_LinkStrField;
        
        /// <remarks/>
        public string PackageLength {
            get {
                return this.packageLengthField;
            }
            set {
                this.packageLengthField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UB_BankCode {
            get {
                return this.uB_BankCodeField;
            }
            set {
                this.uB_BankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UB_ID {
            get {
                return this.uB_IDField;
            }
            set {
                this.uB_IDField = value;
            }
        }
        
        /// <remarks/>
        public string UB_FirmName {
            get {
                return this.uB_FirmNameField;
            }
            set {
                this.uB_FirmNameField = value;
            }
        }
        
        /// <remarks/>
        public string UB_ManageAccount {
            get {
                return this.uB_ManageAccountField;
            }
            set {
                this.uB_ManageAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UB_Money {
            get {
                return this.uB_MoneyField;
            }
            set {
                this.uB_MoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UB_Time {
            get {
                return this.uB_TimeField;
            }
            set {
                this.uB_TimeField = value;
            }
        }
        
        /// <remarks/>
        public string UB_PayerName {
            get {
                return this.uB_PayerNameField;
            }
            set {
                this.uB_PayerNameField = value;
            }
        }
        
        /// <remarks/>
        public string UB_PayerAccount {
            get {
                return this.uB_PayerAccountField;
            }
            set {
                this.uB_PayerAccountField = value;
            }
        }
        
        /// <remarks/>
        public string UB_Type {
            get {
                return this.uB_TypeField;
            }
            set {
                this.uB_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string UB_BankSerialNum {
            get {
                return this.uB_BankSerialNumField;
            }
            set {
                this.uB_BankSerialNumField = value;
            }
        }
        
        /// <remarks/>
        public string UB_SerialNum {
            get {
                return this.uB_SerialNumField;
            }
            set {
                this.uB_SerialNumField = value;
            }
        }
        
        /// <remarks/>
        public string UB_BankSiteID {
            get {
                return this.uB_BankSiteIDField;
            }
            set {
                this.uB_BankSiteIDField = value;
            }
        }
        
        /// <remarks/>
        public string UB_BankTellerID {
            get {
                return this.uB_BankTellerIDField;
            }
            set {
                this.uB_BankTellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string UB_Remark {
            get {
                return this.uB_RemarkField;
            }
            set {
                this.uB_RemarkField = value;
            }
        }
        
        /// <remarks/>
        public string UB_State {
            get {
                return this.uB_StateField;
            }
            set {
                this.uB_StateField = value;
            }
        }
        
        /// <remarks/>
        public string UB_LinkStr {
            get {
                return this.uB_LinkStrField;
            }
            set {
                this.uB_LinkStrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DictionaryEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectsCompletedEventHandler(object sender, SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepositFund[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepositFund[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectCompletedEventHandler(object sender, SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepositFund[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepositFund[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAccountMoneyCompletedEventHandler(object sender, GetAccountMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectnCompletedEventHandler(object sender, SelectnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepositFund[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepositFund[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectDepositInfoListCompletedEventHandler(object sender, SelectDepositInfoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectDepositInfoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectDepositInfoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepositFund[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepositFund[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddUnKownJG_DepositCompletedEventHandler(object sender, AddUnKownJG_DepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUnKownJG_DepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUnKownJG_DepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUnKownJG_DepositCompletedEventHandler(object sender, UpdateUnKownJG_DepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUnKownJG_DepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUnKownJG_DepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectUnKownJG_DepositCompletedEventHandler(object sender, SelectUnKownJG_DepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUnKownJG_DepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUnKownJG_DepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnknowBill[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnknowBill[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUnKownJG_DepositCompletedEventHandler(object sender, DeleteUnKownJG_DepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUnKownJG_DepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUnKownJG_DepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591