//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.BillOperateSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BillOperateSrvSoap", Namespace="http://tempuri.org/")]
    public partial class BillOperateSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectsTodayBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectsInterestBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProduceBillFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BillOperateSrv() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.FinancialRegulationClient_BillOperateSrv_BillOperateSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectsTodayBillCompletedEventHandler SelectsTodayBillCompleted;
        
        /// <remarks/>
        public event SelectsInterestBillCompletedEventHandler SelectsInterestBillCompleted;
        
        /// <remarks/>
        public event ProduceBillFileCompletedEventHandler ProduceBillFileCompleted;
        
        /// <remarks/>
        public event UploadCompletedEventHandler UploadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectsTodayBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillFileCheck[] SelectsTodayBill(BillFileCheck bfc) {
            object[] results = this.Invoke("SelectsTodayBill", new object[] {
                        bfc});
            return ((BillFileCheck[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectsTodayBillAsync(BillFileCheck bfc) {
            this.SelectsTodayBillAsync(bfc, null);
        }
        
        /// <remarks/>
        public void SelectsTodayBillAsync(BillFileCheck bfc, object userState) {
            if ((this.SelectsTodayBillOperationCompleted == null)) {
                this.SelectsTodayBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectsTodayBillOperationCompleted);
            }
            this.InvokeAsync("SelectsTodayBill", new object[] {
                        bfc}, this.SelectsTodayBillOperationCompleted, userState);
        }
        
        private void OnSelectsTodayBillOperationCompleted(object arg) {
            if ((this.SelectsTodayBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectsTodayBillCompleted(this, new SelectsTodayBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectsInterestBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InterestBillCheck[] SelectsInterestBill(InterestBillCheck bfc) {
            object[] results = this.Invoke("SelectsInterestBill", new object[] {
                        bfc});
            return ((InterestBillCheck[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectsInterestBillAsync(InterestBillCheck bfc) {
            this.SelectsInterestBillAsync(bfc, null);
        }
        
        /// <remarks/>
        public void SelectsInterestBillAsync(InterestBillCheck bfc, object userState) {
            if ((this.SelectsInterestBillOperationCompleted == null)) {
                this.SelectsInterestBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectsInterestBillOperationCompleted);
            }
            this.InvokeAsync("SelectsInterestBill", new object[] {
                        bfc}, this.SelectsInterestBillOperationCompleted, userState);
        }
        
        private void OnSelectsInterestBillOperationCompleted(object arg) {
            if ((this.SelectsInterestBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectsInterestBillCompleted(this, new SelectsInterestBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProduceBillFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProduceBillFile(string[] bill, string filepath, string filename) {
            object[] results = this.Invoke("ProduceBillFile", new object[] {
                        bill,
                        filepath,
                        filename});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProduceBillFileAsync(string[] bill, string filepath, string filename) {
            this.ProduceBillFileAsync(bill, filepath, filename, null);
        }
        
        /// <remarks/>
        public void ProduceBillFileAsync(string[] bill, string filepath, string filename, object userState) {
            if ((this.ProduceBillFileOperationCompleted == null)) {
                this.ProduceBillFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProduceBillFileOperationCompleted);
            }
            this.InvokeAsync("ProduceBillFile", new object[] {
                        bill,
                        filepath,
                        filename}, this.ProduceBillFileOperationCompleted, userState);
        }
        
        private void OnProduceBillFileOperationCompleted(object arg) {
            if ((this.ProduceBillFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProduceBillFileCompleted(this, new ProduceBillFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Upload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Upload(string userId, string pwd, string filepath, string filename, string ftpPath) {
            object[] results = this.Invoke("Upload", new object[] {
                        userId,
                        pwd,
                        filepath,
                        filename,
                        ftpPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadAsync(string userId, string pwd, string filepath, string filename, string ftpPath) {
            this.UploadAsync(userId, pwd, filepath, filename, ftpPath, null);
        }
        
        /// <remarks/>
        public void UploadAsync(string userId, string pwd, string filepath, string filename, string ftpPath, object userState) {
            if ((this.UploadOperationCompleted == null)) {
                this.UploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadOperationCompleted);
            }
            this.InvokeAsync("Upload", new object[] {
                        userId,
                        pwd,
                        filepath,
                        filename,
                        ftpPath}, this.UploadOperationCompleted, userState);
        }
        
        private void OnUploadOperationCompleted(object arg) {
            if ((this.UploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadCompleted(this, new UploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BillFileCheck {
        
        private string bussinessCodeField;
        
        private string certificateNumField;
        
        private string regulatoryAccountField;
        
        private string firmNameField;
        
        private string tradeTypeField;
        
        private System.Nullable<decimal> tradeFundAmountField;
        
        private string tradeObjectField;
        
        private string tradeMarkField;
        
        private string projectCodeField;
        
        private System.Nullable<System.DateTime> timeField;
        
        /// <remarks/>
        public string BussinessCode {
            get {
                return this.bussinessCodeField;
            }
            set {
                this.bussinessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CertificateNum {
            get {
                return this.certificateNumField;
            }
            set {
                this.certificateNumField = value;
            }
        }
        
        /// <remarks/>
        public string RegulatoryAccount {
            get {
                return this.regulatoryAccountField;
            }
            set {
                this.regulatoryAccountField = value;
            }
        }
        
        /// <remarks/>
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        public string TradeType {
            get {
                return this.tradeTypeField;
            }
            set {
                this.tradeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TradeFundAmount {
            get {
                return this.tradeFundAmountField;
            }
            set {
                this.tradeFundAmountField = value;
            }
        }
        
        /// <remarks/>
        public string TradeObject {
            get {
                return this.tradeObjectField;
            }
            set {
                this.tradeObjectField = value;
            }
        }
        
        /// <remarks/>
        public string TradeMark {
            get {
                return this.tradeMarkField;
            }
            set {
                this.tradeMarkField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InterestBillCheck {
        
        private string regulatoryAccountField;
        
        private System.Nullable<decimal> tradeFundAmountField;
        
        private System.Nullable<System.DateTime> timeField;
        
        private string projectCodeField;
        
        private string tradeObjectField;
        
        private string tradeMarkField;
        
        private string bankSerialNumberField;
        
        private string instructionField;
        
        /// <remarks/>
        public string RegulatoryAccount {
            get {
                return this.regulatoryAccountField;
            }
            set {
                this.regulatoryAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TradeFundAmount {
            get {
                return this.tradeFundAmountField;
            }
            set {
                this.tradeFundAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TradeObject {
            get {
                return this.tradeObjectField;
            }
            set {
                this.tradeObjectField = value;
            }
        }
        
        /// <remarks/>
        public string TradeMark {
            get {
                return this.tradeMarkField;
            }
            set {
                this.tradeMarkField = value;
            }
        }
        
        /// <remarks/>
        public string BankSerialNumber {
            get {
                return this.bankSerialNumberField;
            }
            set {
                this.bankSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectsTodayBillCompletedEventHandler(object sender, SelectsTodayBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectsTodayBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectsTodayBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillFileCheck[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillFileCheck[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectsInterestBillCompletedEventHandler(object sender, SelectsInterestBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectsInterestBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectsInterestBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterestBillCheck[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterestBillCheck[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ProduceBillFileCompletedEventHandler(object sender, ProduceBillFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProduceBillFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProduceBillFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadCompletedEventHandler(object sender, UploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591