//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.ParmItemSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParmItemSrvSoap", Namespace="http://tempuri.org/")]
    public partial class ParmItemSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectTheParmItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ParmItemSrv() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.HSIS_Client_ParmItemSrv_ParmItemSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectTheParmItemCompletedEventHandler SelectTheParmItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectTheParmItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParmItem[] SelectTheParmItem(ParmItem p) {
            object[] results = this.Invoke("SelectTheParmItem", new object[] {
                        p});
            return ((ParmItem[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectTheParmItemAsync(ParmItem p) {
            this.SelectTheParmItemAsync(p, null);
        }
        
        /// <remarks/>
        public void SelectTheParmItemAsync(ParmItem p, object userState) {
            if ((this.SelectTheParmItemOperationCompleted == null)) {
                this.SelectTheParmItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTheParmItemOperationCompleted);
            }
            this.InvokeAsync("SelectTheParmItem", new object[] {
                        p}, this.SelectTheParmItemOperationCompleted, userState);
        }
        
        private void OnSelectTheParmItemOperationCompleted(object arg) {
            if ((this.SelectTheParmItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTheParmItemCompleted(this, new SelectTheParmItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParmItem {
        
        private string pI_SETCODEField;
        
        private string pI_ITEMCODEField;
        
        private string pI_ITEMNAMEField;
        
        private string pI_COLORVALUEField;
        
        private System.Nullable<int> pI_ITEMVALUEField;
        
        private string pI_PARENTSETCODEField;
        
        private bool isCheckedField;
        
        /// <remarks/>
        public string PI_SETCODE {
            get {
                return this.pI_SETCODEField;
            }
            set {
                this.pI_SETCODEField = value;
            }
        }
        
        /// <remarks/>
        public string PI_ITEMCODE {
            get {
                return this.pI_ITEMCODEField;
            }
            set {
                this.pI_ITEMCODEField = value;
            }
        }
        
        /// <remarks/>
        public string PI_ITEMNAME {
            get {
                return this.pI_ITEMNAMEField;
            }
            set {
                this.pI_ITEMNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PI_COLORVALUE {
            get {
                return this.pI_COLORVALUEField;
            }
            set {
                this.pI_COLORVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PI_ITEMVALUE {
            get {
                return this.pI_ITEMVALUEField;
            }
            set {
                this.pI_ITEMVALUEField = value;
            }
        }
        
        /// <remarks/>
        public string PI_PARENTSETCODE {
            get {
                return this.pI_PARENTSETCODEField;
            }
            set {
                this.pI_PARENTSETCODEField = value;
            }
        }
        
        /// <remarks/>
        public bool IsChecked {
            get {
                return this.isCheckedField;
            }
            set {
                this.isCheckedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectTheParmItemCompletedEventHandler(object sender, SelectTheParmItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTheParmItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTheParmItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParmItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParmItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591