//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace BaseClient.BaseManageSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BaseManageSrvSoap", Namespace="http://tempuri.org/")]
    public partial class BaseManageSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMenuItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModMenuItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BaseManageSrv() {
            this.Url = global::BaseClient.Properties.Settings.Default.BaseClient_BaseManageSrv_BaseManageSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMenuCompletedEventHandler GetMenuCompleted;
        
        /// <remarks/>
        public event GetMenuItemsCompletedEventHandler GetMenuItemsCompleted;
        
        /// <remarks/>
        public event AddMenuItemCompletedEventHandler AddMenuItemCompleted;
        
        /// <remarks/>
        public event DeleteMenuItemCompletedEventHandler DeleteMenuItemCompleted;
        
        /// <remarks/>
        public event ModMenuItemCompletedEventHandler ModMenuItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuItem[] GetMenu() {
            object[] results = this.Invoke("GetMenu", new object[0]);
            return ((MenuItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMenuAsync() {
            this.GetMenuAsync(null);
        }
        
        /// <remarks/>
        public void GetMenuAsync(object userState) {
            if ((this.GetMenuOperationCompleted == null)) {
                this.GetMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenuOperationCompleted);
            }
            this.InvokeAsync("GetMenu", new object[0], this.GetMenuOperationCompleted, userState);
        }
        
        private void OnGetMenuOperationCompleted(object arg) {
            if ((this.GetMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenuCompleted(this, new GetMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMenuItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuItem[] GetMenuItems() {
            object[] results = this.Invoke("GetMenuItems", new object[0]);
            return ((MenuItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMenuItemsAsync() {
            this.GetMenuItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetMenuItemsAsync(object userState) {
            if ((this.GetMenuItemsOperationCompleted == null)) {
                this.GetMenuItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenuItemsOperationCompleted);
            }
            this.InvokeAsync("GetMenuItems", new object[0], this.GetMenuItemsOperationCompleted, userState);
        }
        
        private void OnGetMenuItemsOperationCompleted(object arg) {
            if ((this.GetMenuItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenuItemsCompleted(this, new GetMenuItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMenuItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMenuItem(MenuItem mi, out string e) {
            object[] results = this.Invoke("AddMenuItem", new object[] {
                        mi});
            e = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMenuItemAsync(MenuItem mi) {
            this.AddMenuItemAsync(mi, null);
        }
        
        /// <remarks/>
        public void AddMenuItemAsync(MenuItem mi, object userState) {
            if ((this.AddMenuItemOperationCompleted == null)) {
                this.AddMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMenuItemOperationCompleted);
            }
            this.InvokeAsync("AddMenuItem", new object[] {
                        mi}, this.AddMenuItemOperationCompleted, userState);
        }
        
        private void OnAddMenuItemOperationCompleted(object arg) {
            if ((this.AddMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMenuItemCompleted(this, new AddMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMenuItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMenuItem(MenuItem mi, out string e) {
            object[] results = this.Invoke("DeleteMenuItem", new object[] {
                        mi});
            e = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMenuItemAsync(MenuItem mi) {
            this.DeleteMenuItemAsync(mi, null);
        }
        
        /// <remarks/>
        public void DeleteMenuItemAsync(MenuItem mi, object userState) {
            if ((this.DeleteMenuItemOperationCompleted == null)) {
                this.DeleteMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMenuItemOperationCompleted);
            }
            this.InvokeAsync("DeleteMenuItem", new object[] {
                        mi}, this.DeleteMenuItemOperationCompleted, userState);
        }
        
        private void OnDeleteMenuItemOperationCompleted(object arg) {
            if ((this.DeleteMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMenuItemCompleted(this, new DeleteMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModMenuItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModMenuItem(MenuItem mi, out string e) {
            object[] results = this.Invoke("ModMenuItem", new object[] {
                        mi});
            e = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModMenuItemAsync(MenuItem mi) {
            this.ModMenuItemAsync(mi, null);
        }
        
        /// <remarks/>
        public void ModMenuItemAsync(MenuItem mi, object userState) {
            if ((this.ModMenuItemOperationCompleted == null)) {
                this.ModMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModMenuItemOperationCompleted);
            }
            this.InvokeAsync("ModMenuItem", new object[] {
                        mi}, this.ModMenuItemOperationCompleted, userState);
        }
        
        private void OnModMenuItemOperationCompleted(object arg) {
            if ((this.ModMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModMenuItemCompleted(this, new ModMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MenuItem {
        
        private string idField;
        
        private string codeField;
        
        private string nameField;
        
        private string iconField;
        
        private string pathField;
        
        private int layerField;
        
        private string parentField;
        
        private string isDetailField;
        
        private string invokingConfigField;
        
        private string assemblyNameField;
        
        private string windowNameField;
        
        private int ordinalField;
        
        private MenuItem[] childrenField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public int Layer {
            get {
                return this.layerField;
            }
            set {
                this.layerField = value;
            }
        }
        
        /// <remarks/>
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        public string IsDetail {
            get {
                return this.isDetailField;
            }
            set {
                this.isDetailField = value;
            }
        }
        
        /// <remarks/>
        public string InvokingConfig {
            get {
                return this.invokingConfigField;
            }
            set {
                this.invokingConfigField = value;
            }
        }
        
        /// <remarks/>
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public string WindowName {
            get {
                return this.windowNameField;
            }
            set {
                this.windowNameField = value;
            }
        }
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public MenuItem[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetMenuCompletedEventHandler(object sender, GetMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetMenuItemsCompletedEventHandler(object sender, GetMenuItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenuItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenuItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddMenuItemCompletedEventHandler(object sender, AddMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string e {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteMenuItemCompletedEventHandler(object sender, DeleteMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string e {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ModMenuItemCompletedEventHandler(object sender, ModMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string e {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591