//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace FundsRegulatoryClient.JG_PaymentSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JG_PaymentServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DictionaryEntry[]))]
    public partial class JG_PaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpPayMentInfoByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpPayMentInfoInterestByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback selectYEByXybhOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectJG_PaymentInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectThePaymentInfoByIntervalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JG_PaymentService() {
            this.Url = global::FundsRegulatoryClient.Properties.Settings.Default.FinancialRegulationClient_JG_PaymentSrv_JG_PaymentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event SelectsCompletedEventHandler SelectsCompleted;
        
        /// <remarks/>
        public event SelectCompletedEventHandler SelectCompleted;
        
        /// <remarks/>
        public event UpPayMentInfoByIdCompletedEventHandler UpPayMentInfoByIdCompleted;
        
        /// <remarks/>
        public event UpPayMentInfoInterestByIdCompletedEventHandler UpPayMentInfoInterestByIdCompleted;
        
        /// <remarks/>
        public event selectYEByXybhCompletedEventHandler selectYEByXybhCompleted;
        
        /// <remarks/>
        public event SelectJG_PaymentInterestCompletedEventHandler SelectJG_PaymentInterestCompleted;
        
        /// <remarks/>
        public event SelectThePaymentInfoByIntervalCompletedEventHandler SelectThePaymentInfoByIntervalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(FundPayment o) {
            object[] results = this.Invoke("Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(FundPayment o) {
            this.AddAsync(o, null);
        }
        
        /// <remarks/>
        public void AddAsync(FundPayment o, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        o}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update(FundPayment o) {
            object[] results = this.Invoke("Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(FundPayment o) {
            this.UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(FundPayment o, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        o}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete(FundPayment o) {
            object[] results = this.Invoke("Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(FundPayment o) {
            this.DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(FundPayment o, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        o}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FundPayment[] Selects() {
            object[] results = this.Invoke("Selects", new object[0]);
            return ((FundPayment[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectsAsync() {
            this.SelectsAsync(null);
        }
        
        /// <remarks/>
        public void SelectsAsync(object userState) {
            if ((this.SelectsOperationCompleted == null)) {
                this.SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectsOperationCompleted);
            }
            this.InvokeAsync("Selects", new object[0], this.SelectsOperationCompleted, userState);
        }
        
        private void OnSelectsOperationCompleted(object arg) {
            if ((this.SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectsCompleted(this, new SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FundPayment[] Select(FundPayment o) {
            object[] results = this.Invoke("Select", new object[] {
                        o});
            return ((FundPayment[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectAsync(FundPayment o) {
            this.SelectAsync(o, null);
        }
        
        /// <remarks/>
        public void SelectAsync(FundPayment o, object userState) {
            if ((this.SelectOperationCompleted == null)) {
                this.SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOperationCompleted);
            }
            this.InvokeAsync("Select", new object[] {
                        o}, this.SelectOperationCompleted, userState);
        }
        
        private void OnSelectOperationCompleted(object arg) {
            if ((this.SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompleted(this, new SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpPayMentInfoById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpPayMentInfoById(FundPayment o) {
            object[] results = this.Invoke("UpPayMentInfoById", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpPayMentInfoByIdAsync(FundPayment o) {
            this.UpPayMentInfoByIdAsync(o, null);
        }
        
        /// <remarks/>
        public void UpPayMentInfoByIdAsync(FundPayment o, object userState) {
            if ((this.UpPayMentInfoByIdOperationCompleted == null)) {
                this.UpPayMentInfoByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpPayMentInfoByIdOperationCompleted);
            }
            this.InvokeAsync("UpPayMentInfoById", new object[] {
                        o}, this.UpPayMentInfoByIdOperationCompleted, userState);
        }
        
        private void OnUpPayMentInfoByIdOperationCompleted(object arg) {
            if ((this.UpPayMentInfoByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpPayMentInfoByIdCompleted(this, new UpPayMentInfoByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpPayMentInfoInterestById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpPayMentInfoInterestById(FundPayment o) {
            object[] results = this.Invoke("UpPayMentInfoInterestById", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpPayMentInfoInterestByIdAsync(FundPayment o) {
            this.UpPayMentInfoInterestByIdAsync(o, null);
        }
        
        /// <remarks/>
        public void UpPayMentInfoInterestByIdAsync(FundPayment o, object userState) {
            if ((this.UpPayMentInfoInterestByIdOperationCompleted == null)) {
                this.UpPayMentInfoInterestByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpPayMentInfoInterestByIdOperationCompleted);
            }
            this.InvokeAsync("UpPayMentInfoInterestById", new object[] {
                        o}, this.UpPayMentInfoInterestByIdOperationCompleted, userState);
        }
        
        private void OnUpPayMentInfoInterestByIdOperationCompleted(object arg) {
            if ((this.UpPayMentInfoInterestByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpPayMentInfoInterestByIdCompleted(this, new UpPayMentInfoInterestByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectYEByXybh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal selectYEByXybh(string xybh) {
            object[] results = this.Invoke("selectYEByXybh", new object[] {
                        xybh});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void selectYEByXybhAsync(string xybh) {
            this.selectYEByXybhAsync(xybh, null);
        }
        
        /// <remarks/>
        public void selectYEByXybhAsync(string xybh, object userState) {
            if ((this.selectYEByXybhOperationCompleted == null)) {
                this.selectYEByXybhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselectYEByXybhOperationCompleted);
            }
            this.InvokeAsync("selectYEByXybh", new object[] {
                        xybh}, this.selectYEByXybhOperationCompleted, userState);
        }
        
        private void OnselectYEByXybhOperationCompleted(object arg) {
            if ((this.selectYEByXybhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selectYEByXybhCompleted(this, new selectYEByXybhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectJG_PaymentInterest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FundPayment[] SelectJG_PaymentInterest(FundPayment o) {
            object[] results = this.Invoke("SelectJG_PaymentInterest", new object[] {
                        o});
            return ((FundPayment[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectJG_PaymentInterestAsync(FundPayment o) {
            this.SelectJG_PaymentInterestAsync(o, null);
        }
        
        /// <remarks/>
        public void SelectJG_PaymentInterestAsync(FundPayment o, object userState) {
            if ((this.SelectJG_PaymentInterestOperationCompleted == null)) {
                this.SelectJG_PaymentInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectJG_PaymentInterestOperationCompleted);
            }
            this.InvokeAsync("SelectJG_PaymentInterest", new object[] {
                        o}, this.SelectJG_PaymentInterestOperationCompleted, userState);
        }
        
        private void OnSelectJG_PaymentInterestOperationCompleted(object arg) {
            if ((this.SelectJG_PaymentInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectJG_PaymentInterestCompleted(this, new SelectJG_PaymentInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectThePaymentInfoByInterval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FundPayment[] SelectThePaymentInfoByInterval([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] array) {
            object[] results = this.Invoke("SelectThePaymentInfoByInterval", new object[] {
                        array});
            return ((FundPayment[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectThePaymentInfoByIntervalAsync(DictionaryEntry[] array) {
            this.SelectThePaymentInfoByIntervalAsync(array, null);
        }
        
        /// <remarks/>
        public void SelectThePaymentInfoByIntervalAsync(DictionaryEntry[] array, object userState) {
            if ((this.SelectThePaymentInfoByIntervalOperationCompleted == null)) {
                this.SelectThePaymentInfoByIntervalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectThePaymentInfoByIntervalOperationCompleted);
            }
            this.InvokeAsync("SelectThePaymentInfoByInterval", new object[] {
                        array}, this.SelectThePaymentInfoByIntervalOperationCompleted, userState);
        }
        
        private void OnSelectThePaymentInfoByIntervalOperationCompleted(object arg) {
            if ((this.SelectThePaymentInfoByIntervalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectThePaymentInfoByIntervalCompleted(this, new SelectThePaymentInfoByIntervalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FundPayment {
        
        private string packageLengthField;
        
        private string businessCodeField;
        
        private string bankCodeField;
        
        private string payIDField;
        
        private string paymentIDField;
        
        private System.Nullable<decimal> paymentAmountField;
        
        private string firmNameField;
        
        private string firmOperatorNameField;
        
        private string firmOperatorIDField;
        
        private string paymentBankField;
        
        private string bankSiteIDField;
        
        private string bankTellerIDField;
        
        private string serialNumberField;
        
        private string paymentInstrField;
        
        private System.Nullable<System.DateTime> paymentTimeField;
        
        private string bankSerialNumberField;
        
        private string receiverAccountField;
        
        private string receiverNameField;
        
        private string receiveBankField;
        
        private string payAccountField;
        
        private string payNameField;
        
        private string payStateField;
        
        private string projectCodeField;
        
        private System.Nullable<System.DateTime> paymentConfirmTimeField;
        
        private string reverseInstrField;
        
        private System.Nullable<System.DateTime> reverseTimeField;
        
        /// <remarks/>
        public string PackageLength {
            get {
                return this.packageLengthField;
            }
            set {
                this.packageLengthField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PayID {
            get {
                return this.payIDField;
            }
            set {
                this.payIDField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentID {
            get {
                return this.paymentIDField;
            }
            set {
                this.paymentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirmOperatorName {
            get {
                return this.firmOperatorNameField;
            }
            set {
                this.firmOperatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirmOperatorID {
            get {
                return this.firmOperatorIDField;
            }
            set {
                this.firmOperatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentBank {
            get {
                return this.paymentBankField;
            }
            set {
                this.paymentBankField = value;
            }
        }
        
        /// <remarks/>
        public string BankSiteID {
            get {
                return this.bankSiteIDField;
            }
            set {
                this.bankSiteIDField = value;
            }
        }
        
        /// <remarks/>
        public string BankTellerID {
            get {
                return this.bankTellerIDField;
            }
            set {
                this.bankTellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentInstr {
            get {
                return this.paymentInstrField;
            }
            set {
                this.paymentInstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PaymentTime {
            get {
                return this.paymentTimeField;
            }
            set {
                this.paymentTimeField = value;
            }
        }
        
        /// <remarks/>
        public string BankSerialNumber {
            get {
                return this.bankSerialNumberField;
            }
            set {
                this.bankSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverAccount {
            get {
                return this.receiverAccountField;
            }
            set {
                this.receiverAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveBank {
            get {
                return this.receiveBankField;
            }
            set {
                this.receiveBankField = value;
            }
        }
        
        /// <remarks/>
        public string PayAccount {
            get {
                return this.payAccountField;
            }
            set {
                this.payAccountField = value;
            }
        }
        
        /// <remarks/>
        public string PayName {
            get {
                return this.payNameField;
            }
            set {
                this.payNameField = value;
            }
        }
        
        /// <remarks/>
        public string PayState {
            get {
                return this.payStateField;
            }
            set {
                this.payStateField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PaymentConfirmTime {
            get {
                return this.paymentConfirmTimeField;
            }
            set {
                this.paymentConfirmTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReverseInstr {
            get {
                return this.reverseInstrField;
            }
            set {
                this.reverseInstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReverseTime {
            get {
                return this.reverseTimeField;
            }
            set {
                this.reverseTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DictionaryEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectsCompletedEventHandler(object sender, SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FundPayment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FundPayment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectCompletedEventHandler(object sender, SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FundPayment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FundPayment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpPayMentInfoByIdCompletedEventHandler(object sender, UpPayMentInfoByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpPayMentInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpPayMentInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpPayMentInfoInterestByIdCompletedEventHandler(object sender, UpPayMentInfoInterestByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpPayMentInfoInterestByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpPayMentInfoInterestByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void selectYEByXybhCompletedEventHandler(object sender, selectYEByXybhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selectYEByXybhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selectYEByXybhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectJG_PaymentInterestCompletedEventHandler(object sender, SelectJG_PaymentInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectJG_PaymentInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectJG_PaymentInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FundPayment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FundPayment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SelectThePaymentInfoByIntervalCompletedEventHandler(object sender, SelectThePaymentInfoByIntervalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectThePaymentInfoByIntervalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectThePaymentInfoByIntervalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FundPayment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FundPayment[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591